<<<<<<< HEAD:service/rpc/cart/etc/cart.yaml
Name: cart.rpc
ListenOn: 0.0.0.0:6664

Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: cart.rpc
=======
Name: Product
Host: 0.0.0.0
Port: 6002
>>>>>>> 8002f90cd53259a53a26dc23ec27bdbcf3ea6389:service/product/api/etc/product.yaml

Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/api?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: 127.0.0.1:6379
    Pass:
    Type: node

Auth:
  AccessSecret: uOvKLmVfztaXGpNYd4Z0I1SiT7MweJhl
  AccessExpire: 86400

ProductRpc:
  Etcd:
    Hosts:
      - 127.0.0.1:2379
    Key: product.rpc