// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	UserName string `json:"userName"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Uid          int64  `json:"uid"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type UserInfoResponse struct {
	Id               int64  `json:"uid"`
	UserName         string `json:"userName"`
	CurrentAuthority string `json:"currentAuthority"`
}
