// Code generated by goctl. DO NOT EDIT.
package types

type AuthCodeRequest struct {
	Code string `json:"code"`
}

type AuthCodeCodeResponse struct {
	OpenID   string           `json:"openID"`
	IsReg    bool             `json:"isReg"`
	UserInfo UserInfoResponse `json:"userInfo"`
}

type DecryptRequest struct {
	OpenId        string `json:"openId"`
	EncryptedData string `json:"encryptedData"`
	Iv            string `json:"iv"`
}

type DecryptResponse struct {
	Mobile string `json:"mobile"`
}

type RegRequest struct {
	OpenId string `json:"openId"`
	Mobile string `json:"mobile"`
}

type BindRequest struct {
	NickName string `json:"nickName"`
	Avatar   string `json:"avatar"`
}

type UserInfoResponse struct {
	Id     int64  `json:"uid"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
	Token  string `json:"token"`
}

type SuccessResponse struct {
}

type SendSmsReq struct {
}

type SendSmsResp struct {
}

type WxPayCallBackReq struct {
}

type WxPayCallBackResp struct {
	ReturnCode string `json:"return_code"`
}
