// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type LoginResponse struct {
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
}

type RegisterRequest struct {
	Name     string `json:"name"`
	Gender   int64  `json:"gender"`
	Mobile   string `json:"mobile"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}

type UserInfoResponse struct {
	Id     int64  `json:"id"`
	Name   string `json:"name"`
	Gender int64  `json:"gender"`
	Mobile string `json:"mobile"`
}

type CartsItem struct {
	Id        int    `json:"id"`
	GoodsID   int    `json:"goodsId"`
	GoodsName string `json:"goodsName"`
	Num       int    `json:"num"`
}

type CartsListResponse struct {
	List []CartsItem `json:"list"`
}

type CartsAddRequest struct {
	GoodsID int `json:"goodsId"`
	Num     int `json:"num"`
}

type CartsAddResponse struct {
	Id string `json:"id"`
}

type CartsEditRequest struct {
	Id   int `json:"id"`
	Type int `json:"type"`
}

type CartsEditResponse struct {
}

type CartsDelRequest struct {
	Idx int `json:"idx"`
}

type CartsDelResponse struct {
}

type WxPayCallBackReq struct {
}

type WxPayCallBackResp struct {
	ReturnCode string `json:"return_code"`
}
