Name: product.rpc
<<<<<<< HEAD:service/rpc/product/etc/product.yaml
ListenOn: 0.0.0.0:6661
=======
ListenOn: 0.0.0.0:6200
>>>>>>> c3442f2aed4419e018f66e1d844e317db6477f8c:service/product/rpc/etc/product.yaml

Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: product.rpc

Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/api?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: 127.0.0.1:6379
    Type: node
    Pass: