// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"github.com/skywalkerwei/pluton-faster/service/wxapp/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/user/register",
				Handler: RegisterHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/user/userinfo",
				Handler: UserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/carts/list",
				Handler: CartsListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/carts/add",
				Handler: CartsAddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/carts/edit",
				Handler: CartsEditHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/carts/del",
				Handler: CartsDelHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/wxPayCallBack",
				Handler: WxPayCallBackHandler(serverCtx),
			},
		},
	)
}
