Name: product.rpc
ListenOn: 0.0.0.0:7102

Etcd:
  Hosts:
    - 127.0.0.1:2379
  Key: product.rpc

Mysql:
  DataSource: root:123456@tcp(127.0.0.1:3306)/api?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai

CacheRedis:
  - Host: 127.0.0.1:6379
    Type: node
    Pass: