// Code generated by goctl. DO NOT EDIT!
// Source: cart.proto

package server

import (
	"context"

	"github.com/skywalkerwei/pluton-faster/service/rpc/cart/cart"
	"github.com/skywalkerwei/pluton-faster/service/rpc/cart/internal/logic"
	"github.com/skywalkerwei/pluton-faster/service/rpc/cart/internal/svc"
)

type CartServer struct {
	svcCtx *svc.ServiceContext
}

func NewCartServer(svcCtx *svc.ServiceContext) *CartServer {
	return &CartServer{
		svcCtx: svcCtx,
	}
}

func (s *CartServer) List(ctx context.Context, in *cart.ListReq) (*cart.ListResp, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *CartServer) Add(ctx context.Context, in *cart.AddReq) (*cart.AddResp, error) {
	l := logic.NewAddLogic(ctx, s.svcCtx)
	return l.Add(in)
}

func (s *CartServer) Edit(ctx context.Context, in *cart.EditReq) (*cart.EditResp, error) {
	l := logic.NewEditLogic(ctx, s.svcCtx)
	return l.Edit(in)
}

func (s *CartServer) Del(ctx context.Context, in *cart.DelReq) (*cart.DelResp, error) {
	l := logic.NewDelLogic(ctx, s.svcCtx)
	return l.Del(in)
}
