// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	auth "github.com/skywalkerwei/pluton-faster/service/api/wxapp/internal/handler/auth"
	callBack "github.com/skywalkerwei/pluton-faster/service/api/wxapp/internal/handler/callBack"
	other "github.com/skywalkerwei/pluton-faster/service/api/wxapp/internal/handler/other"
	"github.com/skywalkerwei/pluton-faster/service/api/wxapp/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/code",
				Handler: auth.CodeHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/decrypt",
				Handler: auth.DecryptHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/api/auth/reg",
				Handler: auth.RegHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/api/auth/me",
				Handler: auth.MeHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/api/auth/bind",
				Handler: auth.BindHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/SendSms",
				Handler: other.SendSmsHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/callBack/wxPay",
				Handler: callBack.WxPayHandler(serverCtx),
			},
		},
	)
}
